version: "3.8"

services:
  ecommerce-spring:
    image: mysql:latest
    container_name: stylish-online-store
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis-cart-spring:
    image: redis:latest
    container_name: cart-spring
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - ecommerce-spring

volumes:
  redis-data:
  mysql-data:
  keycloak: